### ISSUE TITLE
Websocket should be retried after failure

### ISSUE THREAD

**Issue by sdague** [Qiskit/qiskit-ibmq-provider#331] opened 2019-09-04 18:34 UTC
There are many reasons why the websocket service might break a connection. Today, if the websocket for status fails for any reason, qiskit falls back to polling.

This should be avoided. The websocket should be reconnected to after any hangup.

**Comment by diego-plan9** [comment] 2019-09-05 08:01
Possible duplicate of #322 - can you check if the related issue and PR covers the issue?

**Comment by sdague** [comment] 2019-09-06 13:36
The fix listed above a single retry, which I think is the wrong fix. This should be done per a normal retry loop, try a couple of times, and if successful, reset the retry count. Falling back to polling should be discouraged.

**Comment by jyu00** [comment] 2019-09-06 13:56
It's easy enough to change the retry in the fix from a boolean to a count. However, how many time is considered "sufficient retries"? We picked retrying once because if it's just a blip then once should be enough. Do you have specific scenarios in mind that would require multiple retries?

**Comment by sdague** [comment] 2019-09-06 14:12
On the REST side the retry count is 5 - https://github.com/Qiskit/qiskit-ibmq-provider/blob/4a0c29f6f1ec4eff7a079d355d5d2cc34e7302b7/qiskit/providers/ibmq/api_v2/session.py#L48, with a delay between connects to handle network issues. That's probably a good baseline.

The other thing about websockets being long lived connections, is that a successful connection should reset the counter. From what I can tell in looking through the code, the retry flag is only set at the beginning - https://github.com/Qiskit/qiskit-ibmq-provider/blob/4a0c29f6f1ec4eff7a079d355d5d2cc34e7302b7/qiskit/providers/ibmq/api_v2/clients/websocket.py#L158 

If you make it here https://github.com/Qiskit/qiskit-ibmq-provider/blob/4a0c29f6f1ec4eff7a079d355d5d2cc34e7302b7/qiskit/providers/ibmq/api_v2/clients/websocket.py#L178 I think the retry counter should be reset.

Because the servers are running in pods, there are many reasons they might go down, including rolling upgrades. And for long running jobs that are taking an hour to return, I think seeing a couple of interuptions is not unexpected.

**Comment by luisg5** [comment] 2019-10-02 20:05
Closed via #341.

**Closed by luisg5** 2019-10-02 20:05 UTC
Labels: type: bug
