### ISSUE TITLE
Every job is in the RUNNING state

### ISSUE THREAD

**Issue by ryan-woo** [Qiskit/qiskit-ibmq-provider#675] opened 2020-05-22 17:01 UTC
### Information

- **Qiskit IBMQ Provider version**:
```
>>> qiskit._get_qiskit_versions()
{'qiskit-terra': '0.14.1', 'qiskit-aer': '0.5.1', 'qiskit-ignis': '0.3.0', 'qiskit-ibmq-provider': '0.7.0', 'qiskit-aqua': '0.7.0', 'qiskit': '0.19.1'}
```
- **API URL or version**: production IQX as of today (How do I find this value??)

- **Python version**: 3.6.4
- **Operating system**: MacOS

### What is the current behavior?
Every job has status RUNNING immediately after VALIDATING but on the iqx page every job is QUEUED.

![image](https://user-images.githubusercontent.com/20371223/82691368-cc19ef80-9c2b-11ea-9d1e-a99b531b332d.png)

### Steps to reproduce the problem
```
# Generate a circuit above here
circ = QuantumCircuit(1,1)
circ.h(0)
circ.measure(0, 0)
for i in range(5):
    execute(circ, ourense)

for job in ourense.active_jobs():
    print(job.job_id(), job.status())
```

```
# output
5ec80449bbcf3e0013051df8 JobStatus.RUNNING
5ec80447414a560012241a3e JobStatus.RUNNING
5ec804464c39180012fd9a48 JobStatus.RUNNING
5ec80444e9fa9900132bdd84 JobStatus.RUNNING
5ec80442bbcf3e0013051df7 JobStatus.RUNNING
```

### What is the expected behavior?
```
# output
5ec80449bbcf3e0013051df8 JobStatus.QUEUED
5ec80447414a560012241a3e JobStatus.QUEUED
5ec804464c39180012fd9a48 JobStatus.QUEUED
5ec80444e9fa9900132bdd84 JobStatus.QUEUED
5ec80442bbcf3e0013051df7 JobStatus.QUEUED
```

### Suggested solutions
This may be an API problem though I'm reporting the problem here first and if determined to not be a bug in provider it can be escalated to the API.

**Comment by jyu00** [comment] 2020-05-27 16:28
This is related to #523 and fixed by #669. 

Prior to the v1 endpoints, if a job's API status is `RUNNING` and has a queue position, then its external status is inferred as `QUEUED`. The problem is that the queue position may not be immediately known, causing the job to go from `VALIDATED` to `RUNNING` before `QUEUED`. The v1 endpoint solved this issue by returning the native `QUEUED` status.

**Closed by jyu00** 2020-05-27 16:28 UTC
Labels: type: bug
